name: "Webhook CI Notification"
description: "Send notifications to a Discord webhook"
inputs:
  content:
    description: "Optional plain message to send before the embed"
    required: false
    default: null
    type: string
  url:
    description: "Discord webhook URL"
    required: true
    type: string
  embeds:
    description: "JSON structure for Discord embeds"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Send webhook notification
      shell: bash
      run: ./entrypoint.sh
