name: "Webhook CI Notification"
description: "Send notifications to a Discord webhook with optional embeds"
inputs:
  content:
    description: "Optional plain message to send before the embed"
    required: false
    default: null
    type: string
  url:
    description: "Discord webhook URL"
    required: true
    type: string
  embeds:
    description: "JSON structure for Discord embeds"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Send webhook notification
      shell: bash
      run: |
        set -e

        # Read inputs
        CONTENT="${{ inputs.content }}"
        WEBHOOK_URL="${{ inputs.url }}"
        EMBEDS="${{ inputs.embeds }}"

        # Validate webhook URL
        if [ -z "$WEBHOOK_URL" ]; then
          echo "Error: Webhook URL is not provided."
          exit 1
        fi

        # Build payload manually
        PAYLOAD="{"
        if [ "$CONTENT" != "null" ] && [ -n "$CONTENT" ]; then
          PAYLOAD+="\"content\": \"$CONTENT\","
        fi
        if [ -n "$EMBEDS" ]; then
          PAYLOAD+="\"embeds\": $EMBEDS"
        else
          # Remove trailing comma if no embeds are present
          PAYLOAD="${PAYLOAD%,}"
        fi
        PAYLOAD+="}"

        # Send payload using curl
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "$WEBHOOK_URL"
