name: Webhook GitHub Integration
description: Sends a notification to a discord webhook
inputs:
  BOT_USERNAME:
    description: 'Username to use for the discord bot message'
    default: 'OpenCraft Builds'
    required: false
    type: string
  BOT_AVATAR:
    description: 'URL to use for the avatar of the discord bot message'
    default: 'https://avatars.githubusercontent.com/u/169554495?s=128'
    required: false
    type: string
  CONTENT:
    description: 'Notification message to send'
    required: true
    type: string
  WEBHOOK_URL:
    description: 'Discord webhook URL'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check if webhook URL is empty
      shell: sh
      run: |
        if [ -z "${{ inputs.WEBHOOK_URL }}" ]; then
          echo "Warning: The webhook URL is empty. Please provide a valid URL." >&2
          exit 1
        fi

    - name: Send the notification
      shell: sh
      run: |
        curl ${{ inputs.WEBHOOK_URL }} -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"username\": \"${{ inputs.BOT_USERNAME }}\", \"avatar_url\": \"${{ inputs.BOT_AVATAR }}\", \"content\": \"${{ inputs.CONTENT }}\" }"
