name: Bug Report (Ingame)
description: 'Create a report to help us improve'
body:
  - type: markdown
    attributes:
      value: 'Please note your issue will be closed without comment if do not fill out the issue checklist and provide ALL the requested information.'
  - type: checkboxes
    attributes:
      label: Checks
      description: Please verify that you've followed these steps.
      options:
        - label: I updated to the latest OpenCraft version.
          required: true
  - type: textarea
    attributes:
      label: 'Describe the bug (be clear and concise)'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Step-by-step reproduction instructions'
      description: 'If possible, please provide minimal example to demonstrate the issue.
      value: |
        1. ...
        2. ...
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected behavior (be clear and concise)'
      description: Tell us in a clear and concise description of what you expected to happen.
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    attributes:
      render: toml
      label: 'What OpenCraft settings are you using?'
      description: 'Paste your OpenCraft settings file here...'
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: 'What OS/version are you seeing the problem?'
      description: 'The build number can be important'
      placeholder: 'ie. Windows 11 Build 26100.3194'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Additional context (optional)'
      description: 'Please add any addition information that might help the investigation'
