blank_issues_enabled: false
contact_links:
  - name: Project setup issues
    url: https://github.com/CiroZDP/oc-cplatform/discussions
    about: The community will guide you to install anything you need.
