name: "Build notifier"
description: "Send notifications to a Discord webhook about some build"
inputs:
  title:
    description: "The title of the embed"
    required: true
    type: string
  content:
    description: "Plain message to send before the embed"
    required: true
    type: string
  url:
    description: "Discord webhook URL"
    required: true
    type: string
  icon:
    description: "The url of the icon of the embed"
    required: true
    type: string
  color:
    description: "The color of the embed"
    required: false
    type: number
    default: 511007

runs:
  using: "composite"
  steps:
    - name: Validate webhook URL
      shell: sh
      run: |
        # Read inputs
        WEBHOOK_URL="${{ inputs.url }}"

        # Validate webhook URL
        if [ -z "$WEBHOOK_URL" ]; then
          echo "Error: Webhook URL is not provided."
          exit 1
        fi

    - name: Send the notification
      shell: sh
      run: |
        CONTENT="${{ inputs.content }}"
        TITLE="${{ inputs.title }}"
        COLOR=${{ inputs.color }}
        ICON=${{ inputs.icon }}

        PAYLOAD='{"content":null,"embeds":[{"title":"$TITLE","description":"$CONTENT","color":$COLOR,"thumbnail":{"url":"$ICON"}}],"attachments":[]}'

        # Send payload using curl
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          "$WEBHOOK_URL"
