name: Download for Linux
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-linux
  cancel-in-progress: true

jobs:
  x32:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install gcc-multilib

      - name: Compile
        shell: bash
        id: compile
        env:
          FLAGS: "-m32"
        run: |
          cd src
          gcc *.c ${{ env.FLAGS }} -o oc-x86

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/oc-x86'
          DEST_NAME: 'OpenCraft-x86'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/CiroZDP/oc-cplatform/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x32 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/CiroZDP/oc-cplatform/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'

  x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        shell: bash
        run: |
          sudo apt-get -y update

      - name: Compile
        shell: bash
        id: compile
        env:
          FLAGS: "-m64"
        run: |
          cd src
          gcc *.c ${{ env.FLAGS }} -o oc-x64

      - name: Upload artifact
        uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/oc-x64'
          DEST_NAME: 'OpenCraft-x64'

      - name: Notify success on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **succeeded**.\\nClick [here](https://github.com/CiroZDP/oc-cplatform/actions/workflows/linux.yml) to see the latest version.'
          color: 511007
          url: '${{ secrets.WEBHOOK_BUILD_SUCCESS_URL }}'

      - name: Notify failure on Discord
        uses: ./.github/actions/build_notifier
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/640px-Tux.svg.png'
          title: 'Linux x64 Build'
          content: 'This workflow has **failed**!\\nClick [here](https://github.com/CiroZDP/oc-cplatform/actions/workflows/linux.yml) to see the latest version.'
          color: 16724016
          url: '${{ secrets.WEBHOOK_BUILD_FAILED_URL }}'
